# Site settings
title: Joao Duraes
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineer. Gadget enthusiast. Auto enthusiast. Gamer. Music lover.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joaoduraes.github.io" # the base hostname & protocol for your site
twitter_username: an0nimo
github_username:  joaoduraes

# Build settings
markdown: kramdown
